[package]
name = "pallet-network"
description = "FRAME pallet for Hypertensor subnet management, staking, and consensus."
version = "4.0.0-dev"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = [
	"derive",
], workspace = true }
scale-info = { features = [
	"derive",
], workspace = true }
frame-benchmarking = { optional = true, workspace = true }
frame-support.workspace = true
frame-system.workspace = true
strum = { version = "0.26.3", features = ["derive"], default-features = false }
strum_macros = { version = "0.26.3", default-features = false }
pallet-balances.workspace = true
log.workspace = true
sp-std.workspace = true
sp-core = { features = ["serde"], workspace = true }
sp-runtime = { workspace = true }
sp-io.workspace = true
libm.workspace = true
pallet-collective = { version = "37.0.0", default-features = false, path = "../collective" }
pallet-treasury.workspace = true
bs58.workspace = true
network-rpc-types.workspace = true

[dev-dependencies]
env_logger = "0.10"
pallet-tx-pause.workspace = true
pallet-babe = { workspace = true, features = ["std"] }
pallet-randomness = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
sp-session = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	"bs58/std",
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"network-rpc-types/std",
	"pallet-balances/std",
	"pallet-collective/std",
	"pallet-treasury/std",
	"pallet-tx-pause/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
]
